//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIHome.Data.All.Access.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTER
    {
        public int COUNTER_ID { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<int> VALUE { get; set; }
        public string URL { get; set; }
    }
}
