//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIHome.Data.All.Access.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGGING
    {
        public int LOGGING_ID { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string MESSAGE { get; set; }
        public string APPLICATION { get; set; }
    }
}
